[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
async-openai = { version = "0.31.1", features = ["_api", "chat-completion", "chat-completion-types"] }
async-trait = "0.1.89"
epub = "=2.1.4"
flume = "0.11.1"
fnv = "1.0.7"
futures = "0.3.31"
gemini-rust = "1.5.0"
isolang = "2.4.0"
itertools = "0.14.0"
log = "0.4"
notify = "8.2.0"
notify-debouncer-full = "0.6.0"
rand = "0.9.2"
regex = "1.11.3"
ringbuffer = "0.16.0"
scraper = "0.22.0"
serde = "1.0.228"
serde_json = "1.0.145"
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
zstd = "0.13.3"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]

[dependencies.foyer]
version = "0.20.0"
features = [
    "serde"
]

[target.'cfg(any(target_os = "macos", target_os = "windows", target_os = "linux"))'.dependencies]
trash = "5.2.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"

[target.'cfg(target_os = "ios")'.dependencies]
objc2 = "0.6.3"
objc2-foundation = "0.3.2"
objc2-ui-kit = "0.3.2"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "translation_bench"
harness = false
