[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
epub = "2.1.4"
flume = "0.11.1"
fnv = "1.0.7"
gemini-rust = "1.5.0"
isolang = "2.4.0"
itertools = "0.14.0"
log = "0.4"
notify = "8.2.0"
notify-debouncer-full = "0.6.0"
rand = "0.9.2"
regex = "1.11.3"
ringbuffer = "0.16.0"
scraper = "0.22.0"
serde = "1.0.228"
serde_json = "1.0.145"
strum = { version = "0.27.2", features = ["derive"] }
tokio = { version = "1.47.1", features = ["full"] }
vfs = "0.12.2"
zstd = "0.13.3"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]

[dependencies.foyer]
version = "0.20.0"
features = [
    "serde"
]
