[package]
name = "library"
version = "0.1.0"
edition = "2024"

[dependencies]
fnv = "1.0.7"
itertools = "0.14.0"
regex = "1.11.3"
ringbuffer = "0.16.0"
vfs = "0.12.2"
zstd = "0.13.3"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]
